### ISSUE TITLE
celery: create a task to cleanup deleted drafts

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-drafts-resources#115]
We soft-delete drafts to keep their version id counter around for optimistic concurrency control. They are needed for about 1 min which is the default time for Elasticsearch configured to keep the deleted id around. 

We should create a celery task that can be configured to run once an hour/day, which will look for soft-deleted drafts and hard-delete them. The task should in principle simply call a service method, and should ensure also that e.g. files are removed.

### Implementation details

- Code should be in Invenio-Drafts-Resources in https://github.com/inveniosoftware/invenio-drafts-resources/tree/master/invenio_drafts_resources/services/records
- The task is dealing with the situation documented here: https://github.com/inveniosoftware/invenio-drafts-resources/blob/master/invenio_drafts_resources/records/api.py#L194-L227

A soft-deleted draft happens in two cases (you'll see it from the service methods where ``draft.delete()`` is called:

1. Create a draft, then publish the draft.
2. Create a draft, publish the draft, edit the record, then delete the draft.

#### Test case

https://github.com/inveniosoftware/invenio-drafts-resources/blob/master/tests/services/test_record_service_files.py

```python


draft = service.create(identity_simple, input_data)
record = service.publish(draft.id, identity_simple)

# Here's the task's job (simplified):
draft_model = service.draft_cls.model_cls
draft_model.query.filter(draft_model.is_deleted == True).delete()
db.session.commit()

# Elasticsearch will complain if we try we don't wait a minute, so disable
# the indexer.
monkeypatch.setattr(service.config, 'indexer_cls', MagicMock())

draft = service.edit(record.id, identity_simple)
data = draft.data
data['metadata']['title'] = "New title"
draft = service.update_draft(record.id, identity_simple, data)
record = service.publish(record.id, identity_simple)
```

Overall, this means that we need a method in the service (e.g ``cleanup_drafts()``), which is able to delegate the cleaning of associated objects to the service components (e.g. DraftFilesComponent, should be responsible on edit to recreate the files from the record.

### Tasks

- [x] create the async task to hard delete drafts (with tests) (see [here](https://github.com/inveniosoftware/invenio-indexer/blob/master/invenio_indexer/tasks.py#L19) an example)
- [x] the new async task will have to be added to the Python entrypoints (see [here](https://github.com/inveniosoftware/invenio-indexer/blob/master/setup.py#L94))
- [x] update [invenio-app-rdm](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/config.py#L246) to add the cron job to CELERY_BEAT

**Comment by ntarocco** [comment]
Useful links:
* Celery: https://docs.celeryproject.org/en/stable/index.html

**Comment by Pineirin** [comment]
Apart from the linked pull request, I had to create another two for other repositories.
https://github.com/inveniosoftware/invenio-indexer/pull/129
https://github.com/inveniosoftware/invenio-app-rdm/pull/810
